server:
  port: 9090

logging:
  level:
    root: INFO
    com.zaxxer.hikari: DEBUG
  file:
    name: logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger - %msg%n"

spring:
  application:
    name: demeter
  profiles:
    active: database